### ISSUE TITLE
Fix GC-198

### ISSUE THREAD

**Issue by Nastia3** [ita-social-projects/GreenCityTests#416]
The following asserts failed:
	The validation message is not equal to the expected one expected [Password must be at least 8 characters in length] but found [Password has contained at least one character of Uppercase letter (A-Z), Lowercase letter (a-z), Digit (0-9), Special character (~`!@#$%^&*()+=_-{}[]|:;”’?/<>,.)]

**Comment by HannaVasiunyk** [comment]
The bug report has already been created and can be found at the [Bug report ](https://github.com/ita-social-projects/GreenCity/issues/1795)
