### ISSUE TITLE
Fix GC-723 Verify that when Title consist of 3 row, then Description consist of 1 row.

### ISSUE THREAD

**Issue by Krynytsky** [ita-social-projects/GreenCityTests#418]
stale element reference: element is not attached to the page document
  (Session info: chrome=87.0.4280.88)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'yurii-K50IP', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-58-generic', java.version: '1.8.0_275'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 87.0.4280.88, chrome: {chromedriverVersion: 87.0.4280.88 (89e2380a3e36c..., userDataDir: /tmp/.com.google.Chrome.SmEkNO}, goog:chromeOptions: {debuggerAddress: localhost:33231}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: 8b4d0a346b4f40119adda4d2674...}
Session ID: 8b4d0a346b4f40119adda4d267492ef5

**Comment by HannaVasiunyk** [comment]
The bug report has already been created and can be found at the [link](https://github.com/ita-social-projects/GreenCity/issues/1919)
